[project]
name = "merit-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mark Reith", email = "mark@appmerit.com" },
    { name = "Nikita Shirobokov", email = "nick@appmerit.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
merit-analyzer = "merit_analyzer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
